import {
  Combine,
  ImageDown,
  Link2,
  FileText,
  Image as ImageIcon,
  Film,
  Type,
  Globe,
  Sparkles,
  AlignLeft,
  KeyRound,
  Braces,
  Binary,
  QrCode,
  Replace,
  Scaling,
  FileImage,
  Scissors,
  Images,
  Crop,
  Shrink,
  Eraser,
  FileAudio,
  AudioLines,
  CaseSensitive,
  Palette,
  Hash,
  RotateCw,
  Stamp,
  ListOrdered,
  Video,
  Clapperboard,
  ScissorsLineDashed,
  LetterText,
  WrapText,
  CopyMinus,
  FlipHorizontal2,
  Repeat,
  Pilcrow,
  GitCompare,
  FileCode2,
  SquarePen,
  Fingerprint,
  CalendarClock,
  Code2,
  KeySquare,
  Regex,
  FileSpreadsheet,
  FileJson,
  Clock,
  Barcode,
  Wifi,
  Contact,
  Calculator,
  Percent,
  Landmark,
  TrendingUp,
  HeartPulse,
  Cake,
  CalendarDays,
  Receipt,
  BadgePercent,
  Shapes,
  ImagePlus,
  ImageOff,
  Pipette,
  SwatchBook,
  Smile,
  LayoutTemplate,
  AppWindow,
  type LucideIcon,
} from "lucide-react";

/**
 * Central map of icon names used across the tool registry and category config.
 * Keeping it explicit (rather than dynamic) keeps the bundle tree-shakeable and
 * makes `icon` fields type-safe via {@link IconName}.
 */
export const iconMap = {
  combine: Combine,
  "image-down": ImageDown,
  link: Link2,
  "file-text": FileText,
  image: ImageIcon,
  film: Film,
  type: Type,
  globe: Globe,
  sparkles: Sparkles,
  "align-left": AlignLeft,
  "key-round": KeyRound,
  braces: Braces,
  binary: Binary,
  "qr-code": QrCode,
  replace: Replace,
  scaling: Scaling,
  "file-image": FileImage,
  scissors: Scissors,
  images: Images,
  crop: Crop,
  shrink: Shrink,
  eraser: Eraser,
  "file-audio": FileAudio,
  "audio-lines": AudioLines,
  "case-sensitive": CaseSensitive,
  palette: Palette,
  hash: Hash,
  "rotate-cw": RotateCw,
  stamp: Stamp,
  "list-ordered": ListOrdered,
  video: Video,
  clapperboard: Clapperboard,
  "scissors-line-dashed": ScissorsLineDashed,
  "letter-text": LetterText,
  "wrap-text": WrapText,
  "copy-minus": CopyMinus,
  "flip-horizontal-2": FlipHorizontal2,
  repeat: Repeat,
  pilcrow: Pilcrow,
  "git-compare": GitCompare,
  "file-code": FileCode2,
  "square-pen": SquarePen,
  fingerprint: Fingerprint,
  "calendar-clock": CalendarClock,
  "code-2": Code2,
  "key-square": KeySquare,
  regex: Regex,
  "file-spreadsheet": FileSpreadsheet,
  "file-json": FileJson,
  clock: Clock,
  barcode: Barcode,
  wifi: Wifi,
  contact: Contact,
  calculator: Calculator,
  percent: Percent,
  landmark: Landmark,
  "trending-up": TrendingUp,
  "heart-pulse": HeartPulse,
  cake: Cake,
  "calendar-days": CalendarDays,
  receipt: Receipt,
  "badge-percent": BadgePercent,
  shapes: Shapes,
  "image-plus": ImagePlus,
  "image-off": ImageOff,
  pipette: Pipette,
  "swatch-book": SwatchBook,
  smile: Smile,
  "layout-template": LayoutTemplate,
  "app-window": AppWindow,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function Icon({
  name,
  className,
}: {
  name: IconName;
  className?: string;
}) {
  const Cmp = iconMap[name];
  return <Cmp className={className} aria-hidden="true" />;
}
